### ISSUE TITLE
Application is down

### ISSUE THREAD

**Issue by nrc4867** [wench/Ao3-Tracker#32]
Hello, It appears that the app went down from the play store. Additionally, it seems that it is no longer able to get data from Ao3 (TrustFailure error). Simply curious if the application is dead or if you plan to restore it. 

[dead store link from wenchy website ](https://play.google.com/store/apps/details?id=net.wenchy.Archive%20Track.reader)

**Comment by wench** [comment]
I delisted the app from the AppStore as I no longer plan on updating the app and didn't think it attractong new users was a good idea.
As such no problems with the app will be fixed and you should consider it dead and should probably access Ao3 using a web browser and not with my app.
